# Generated by Django 5.1.4 on 2025-01-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likour', '0006_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expires_at', models.DateField()),
                ('updated_at', models.DateField()),
            ],
            options={
                'db_table': 'promocodes',
                'ordering': ['id', 'code', 'discount', 'expires_at', 'updated_at'],
            },
        ),
    ]
