# Generated by Django 5.1.4 on 2025-01-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likour', '0008_alter_promocode_options_alter_promocode_table_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number_confirmed',
            new_name='email_confirmed',
        ),
    ]
