# Generated by Django 5.1.4 on 2025-01-02 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likour', '0002_remove_productsku_pack_attribute_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
