# Generated by Django 5.1.4 on 2025-01-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likour', '0003_delete_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
